menu:
    Blog: /
    Archive: /archives/
    University: https://www.uestc.edu.cn/
    GitHub: https://github.com/cyzuestc
    清水河畔: http://bbs.uestc.edu.cn/  

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018
